baseurl = "http://archmage.me/"
disableHugoGeneratorInject = true
disqusShortname = "archmage-me"
enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = false
languageCode = "en-uk"
preserveTaxonomyNames = true
theme = "hugo-bingo"
title = "Arcane Endpoint"
[[menu.main]]
identifier = "Home"
name = "home"
url = "/"
weight = 1
[[menu.main]]
identifier = "Posts"
name = "posts"
url = "posts"
weight = 2
[[menu.main]]
identifier = "Tags"
name = "tags"
url = "tags"
weight = 3
[params]
email = "gitkraken@archmage.me"
[permalinks]
post = "/posts/:slug/"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
