baseurl = "http://archmage.me/"
languageCode = "en-uk"
title = "Arcane Endpoint"
theme = "hugo-bingo"

disableHugoGeneratorInject = true
disqusShortname = "archmage-me"
enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = false
preserveTaxonomyNames = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "author"

[permalinks]
  post = "/posts/:slug/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url= "posts"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url= "tags"
    weight = 3
  [[menu.main]]
    identifier = "valentine-sisters"
    name = "UD_Chars"
    url="valentine-sisters"
    weight = 4

[params]
  email = "gitkraken@archmage.me"