baseURL = "http://archmage.me/"
languageCode = "en-uk"
title = "Arcane Endpoint"
theme = "m10c"
Paginate = 100

[params]
  author = "archmage"
  description = "Hi. I'm Kara \"Archmage\" Valentine."
  [params.style]
   darkestColor = "#675a6e"
   darkColor = "#70426e"
   lightColor = "#e4d3ed"
   lightestColor = "#f7f2fa"
   primaryColor = "#c3a5d4"
   
	[[params.social]]
    name = "github"
    url = "https://github.com/archmage"
  [[params.social]]
    name = "message-circle"
    title = "discord"
    url = "https://discord.gg/3aNgZ5h"
  [[params.social]]
    name = "mail"
    title = "contact"
    url = "/contact"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"